import{test}from'node:test';import assert from'node:assert/strict';import{spawnSync}from'node:child_process';import path from'node:path';import{fileURLToPath}from'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),tool=path.join(root,'scripts/iteration-director.mjs');
function run(a){const r=spawnSync(process.execPath,[tool,...a],{cwd:root,encoding:'utf8'});return{...r,json:r.stdout?JSON.parse(r.stdout):null};}

test('v082 catalogs validate',()=>{const r=run(['validate']);assert.equal(r.status,0,r.stderr);assert.equal(r.json.status,'pass');assert.equal(r.json.face_profiles_v082,5);assert.equal(r.json.fashion_asset_profiles_v082,3);assert.equal(r.json.material_separation_profiles_v082,1);assert.equal(r.json.hand_modes_v082,2);assert.equal(r.json.asset_master_profiles_v082,1);assert.equal(r.json.studio_lighting_profiles_v082,1);assert.equal(r.json.asset_pipeline_presets_v082,1);});
test('beauty first character maps to legacy beauty first',()=>{const r=run(['face-profile-v082','--profile','beauty_first_character']);assert.equal(r.json.base_mode,'beauty_first');assert.equal(r.json.identity_specificity,'high');assert.equal(r.json.maturity_guard,'youthful_18_22');});
test('humanized real light does not force full realism',()=>{const r=run(['face-profile-v082','--profile','humanized_real_light']);assert.equal(r.json.base_mode,'humanized_real');assert.equal(r.json.face_realism,'medium');assert.equal(r.json.beauty_priority,'high');});
test('Default fashion asset uses robe-aware cues without forcing exposed shoes',()=>{const r=run(['fashion-asset-v082']);assert.equal(r.json.profile,'BALANCED_ELEGANT');assert.equal(r.json.controls.torso_length,'fully_preserved');assert.equal(r.json.controls.garment_verticality,'strong');assert.equal(r.json.controls.foot_visibility,'pose_and_garment_dependent');});
test('material separation has four layers',()=>{const r=run(['material-separation-v082']);assert.deepEqual(Object.keys(r.json.layers),['primary_fabric','sheer_overlay','pattern_layer','structure_layer']);assert.match(r.json.prompt_translation.join(' '),/而非平面印花/);});
test('crossed hand mode is generation-time anatomy guard',()=>{const r=run(['hand-pose-v082']);assert.equal(r.json.mode,'elegant_crossed_hands_safe');assert.ok(r.json.requirements.includes('five_digits_each'));assert.ok(r.json.requirements.includes('sleeve_does_not_swallow_finger_roots'));});
test('asset master keeps full silhouette while permitting naturally hidden feet',()=>{const r=run(['asset-master-v082']);assert.ok(r.json.requirements.includes('hair_ornament_fully_visible'));assert.ok(r.json.requirements.includes('natural_footwear_occlusion_allowed'));assert.ok(!r.json.requirements.includes('shoes_fully_visible'));assert.ok(r.json.requirements.includes('hem_spread_controlled'));});
test('studio lighting balances even face exposure and material separation',()=>{const r=run(['studio-light-v082']);assert.equal(r.json.background,'high_key_white_not_clipped');assert.ok(r.json.goals.includes('white_gauze_separates_from_background'));assert.ok(r.json.goals.includes('gold_thread_gets_controlled_highlights'));assert.equal(r.json.fill,'broad_frontal_fill_for_even_face_exposure');assert.ok(r.json.goals.includes('even_face_exposure_with_soft_volume'));assert.ok(r.json.goals.includes('no_dappled_or_hard_hair_shadows'));assert.ok(!r.json.goals.includes('no_flat_even_light'));});
test('asset master plan stages face structure material separately',()=>{const r=run(['asset-master-plan-v082']);assert.equal(r.json.stage_1.round_plan.round,'asset_master_face_refine');assert.equal(r.json.stage_2.round_plan.round,'asset_master_structure_refine');assert.equal(r.json.stage_3.round_plan.round,'asset_master_material_light_refine');});
test('stage 2 locks approved face profile',()=>{const r=run(['asset-master-plan-v082']);assert.ok(r.json.stage_2.round_plan.locked.includes('approved_face_profile'));});
test('stage 3 locks proportion and framing',()=>{const r=run(['asset-master-plan-v082']);assert.ok(r.json.stage_3.round_plan.locked.includes('fashion_asset_proportion'));assert.ok(r.json.stage_3.round_plan.locked.includes('asset_framing'));});
test('generic face routes to asset face refine',()=>{const r=run(['next','--failures','face_template_generic']);assert.equal(r.json.recommended_round,'asset_master_face_refine');});
test('weak P9 asset read routes to structure refine',()=>{const r=run(['next','--failures','p9_asset_read_weak']);assert.equal(r.json.recommended_round,'asset_master_structure_refine');});
test('ambiguous crossed hands route to structure refine',()=>{const r=run(['next','--failures','hand_cross_overlap_ambiguous']);assert.equal(r.json.recommended_round,'asset_master_structure_refine');});
test('merged materials route to material light refine',()=>{const r=run(['next','--failures','material_layers_merged']);assert.equal(r.json.recommended_round,'asset_master_material_light_refine');});
test('flat studio light routes to material light refine',()=>{const r=run(['next','--failures','studio_light_flat']);assert.equal(r.json.recommended_round,'asset_master_material_light_refine');});
test('ancient white plan delivers classified Chinese face proportions hands materials and light',()=>{const r=run(['ancient-white-asset-plan-v082']);assert.equal(r.status,0,r.stderr);const p=r.json.prompt;assert.match(p,/【人物身份与面容】/);assert.match(p,/比例协调、修长好看/);assert.doesNotMatch(p,/七至七点五/);assert.match(p,/一拇指四手指/);assert.match(p,/按实际衣料区分厚薄/);assert.match(p,/纯白无缝棚背景/);assert.equal(r.json.prompt_skeleton.join('\n\n'),p);});
