import{test}from'node:test';import assert from'node:assert/strict';import{spawnSync}from'node:child_process';import path from'node:path';import{fileURLToPath}from'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),tool=path.join(root,'scripts/iteration-director.mjs');
function run(a){const r=spawnSync(process.execPath,[tool,...a],{cwd:root,encoding:'utf8'});return{...r,json:r.stdout?JSON.parse(r.stdout):null};}

test('v082 catalogs validate',()=>{const r=run(['validate']);assert.equal(r.status,0,r.stderr);assert.equal(r.json.status,'pass');assert.equal(r.json.face_profiles_v082,5);assert.equal(r.json.fashion_asset_profiles_v082,2);assert.equal(r.json.material_separation_profiles_v082,1);assert.equal(r.json.hand_modes_v082,2);assert.equal(r.json.asset_master_profiles_v082,1);assert.equal(r.json.studio_lighting_profiles_v082,1);assert.equal(r.json.asset_pipeline_presets_v082,1);});
test('beauty first character maps to legacy beauty first',()=>{const r=run(['face-profile-v082','--profile','beauty_first_character']);assert.equal(r.json.base_mode,'beauty_first');assert.equal(r.json.identity_specificity,'high');assert.equal(r.json.maturity_guard,'youthful_18_22');});
test('humanized real light does not force full realism',()=>{const r=run(['face-profile-v082','--profile','humanized_real_light']);assert.equal(r.json.base_mode,'humanized_real');assert.equal(r.json.face_realism,'medium');assert.equal(r.json.beauty_priority,'high');});
test('P9 fashion asset uses robe-aware cues',()=>{const r=run(['fashion-asset-v082']);assert.equal(r.json.profile,'P9_FASHION_ASSET');assert.equal(r.json.controls.torso_length,'fully_preserved');assert.equal(r.json.controls.garment_verticality,'strong');assert.match(r.json.robe_rules.join(' '),/foot-to-hem/);});
test('material separation has four layers',()=>{const r=run(['material-separation-v082']);assert.deepEqual(Object.keys(r.json.layers),['primary_fabric','sheer_overlay','pattern_layer','structure_layer']);assert.match(r.json.prompt_translation.join(' '),/rather than printed/);});
test('crossed hand mode is generation-time anatomy guard',()=>{const r=run(['hand-pose-v082']);assert.equal(r.json.mode,'elegant_crossed_hands_safe');assert.ok(r.json.requirements.includes('five_digits_each'));assert.ok(r.json.requirements.includes('sleeve_does_not_swallow_finger_roots'));});
test('asset master requires full ornament and footwear visibility',()=>{const r=run(['asset-master-v082']);assert.ok(r.json.requirements.includes('hair_ornament_fully_visible'));assert.ok(r.json.requirements.includes('shoes_fully_visible'));assert.ok(r.json.requirements.includes('hem_spread_controlled'));});
test('studio lighting preserves white separation',()=>{const r=run(['studio-light-v082']);assert.equal(r.json.background,'high_key_white_not_clipped');assert.ok(r.json.goals.includes('white_gauze_separates_from_background'));assert.ok(r.json.goals.includes('gold_thread_gets_controlled_highlights'));});
test('asset master plan stages face structure material separately',()=>{const r=run(['asset-master-plan-v082']);assert.equal(r.json.stage_1.round_plan.round,'asset_master_face_refine');assert.equal(r.json.stage_2.round_plan.round,'asset_master_structure_refine');assert.equal(r.json.stage_3.round_plan.round,'asset_master_material_light_refine');});
test('stage 2 locks approved face profile',()=>{const r=run(['asset-master-plan-v082']);assert.ok(r.json.stage_2.round_plan.locked.includes('approved_face_profile'));});
test('stage 3 locks proportion and framing',()=>{const r=run(['asset-master-plan-v082']);assert.ok(r.json.stage_3.round_plan.locked.includes('fashion_asset_proportion'));assert.ok(r.json.stage_3.round_plan.locked.includes('asset_framing'));});
test('generic face routes to asset face refine',()=>{const r=run(['next','--failures','face_template_generic']);assert.equal(r.json.recommended_round,'asset_master_face_refine');});
test('weak P9 asset read routes to structure refine',()=>{const r=run(['next','--failures','p9_asset_read_weak']);assert.equal(r.json.recommended_round,'asset_master_structure_refine');});
test('ambiguous crossed hands route to structure refine',()=>{const r=run(['next','--failures','hand_cross_overlap_ambiguous']);assert.equal(r.json.recommended_round,'asset_master_structure_refine');});
test('merged materials route to material light refine',()=>{const r=run(['next','--failures','material_layers_merged']);assert.equal(r.json.recommended_round,'asset_master_material_light_refine');});
test('flat studio light routes to material light refine',()=>{const r=run(['next','--failures','studio_light_flat']);assert.equal(r.json.recommended_round,'asset_master_material_light_refine');});
test('ancient white plan combines face natural proportions hands materials and studio light',()=>{const r=run(['ancient-white-asset-plan-v082']);const p=r.json.prompt_skeleton.join(' ');assert.match(p,/character-specific facial identity/);assert.match(p,/seven to seven-and-a-half/);assert.doesNotMatch(p,/approximately nine-head/);assert.match(p,/exactly five/);assert.match(p,/Give each specified layer its own physical response/);assert.match(p,/premium high-key studio setup/);});
