import{test}from'node:test';import assert from'node:assert/strict';import{spawnSync}from'node:child_process';import path from'node:path';import{fileURLToPath}from'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),tool=path.join(root,'scripts/iteration-director.mjs');
function run(a){const r=spawnSync(process.execPath,[tool,...a],{cwd:root,encoding:'utf8'});return{...r,json:r.stdout?JSON.parse(r.stdout):null};}

test('v081 catalogs validate',()=>{const r=run(['validate']);assert.equal(r.status,0,r.stderr);assert.equal(r.json.status,'pass');assert.equal(r.json.detail_budget_profiles,2);assert.equal(r.json.highlight_hierarchy_profiles,1);assert.equal(r.json.background_submission_profiles,1);assert.equal(r.json.painterly_edge_profiles,1);assert.equal(r.json.concept_art_hierarchy_profiles,1);});
test('concept art detail budget has three detail tiers',()=>{const r=run(['detail-budget-v081']);assert.equal(r.status,0,r.stderr);assert.equal(r.json.primary_detail.level,'high');assert.equal(r.json.secondary_detail.level,'medium');assert.equal(r.json.atmospheric_detail.level,'low_selective');});
test('face is primary detail and distant architecture atmospheric',()=>{const r=run(['detail-budget-v081']);assert.ok(r.json.primary_detail.regions.includes('face'));assert.ok(r.json.atmospheric_detail.regions.includes('distant_architecture'));});
test('highlight hierarchy focuses face zone and subordinates background',()=>{const r=run(['highlight-hierarchy-v081']);assert.ok(r.json.primary_highlights.includes('face_adjacent_zone'));assert.ok(r.json.tertiary_highlights.includes('distant_architecture'));});
test('background submission reduces hard detail around head',()=>{const r=run(['background-submission-v081']);assert.match(r.json.head_zone_policy,/reduce_hard_detail/);assert.match(r.json.contrast_policy,/below_character_focal_zone/);});
test('painterly edge has crisp soft and lost groups',()=>{const r=run(['painterly-edge-v081']);assert.ok(r.json.crisp_edges.includes('eyes'));assert.ok(r.json.soft_edges.includes('hair_tails'));assert.ok(r.json.lost_edges.includes('mist_architecture_intersections'));});
test('concept art hierarchy binds all four controllers',()=>{const r=run(['concept-art-hierarchy']);assert.equal(r.json.detail_budget,'concept_art_priority');assert.equal(r.json.highlight_hierarchy,'focal_brightness');assert.equal(r.json.background_submission,'monumental_subordinate');assert.equal(r.json.edge_control,'selective_painterly');});
test('hierarchy round locks face mode and style target',()=>{const r=run(['round','--name','concept_art_hierarchy_refine']);assert.ok(r.json.locked.includes('explicit_style_target'));assert.ok(r.json.locked.includes('approved_face_mode'));assert.ok(r.json.locked.includes('garment_structure'));assert.ok(r.json.editable.includes('detail_budget'));});
test('hierarchy plan does not reopen motion palette or costume',()=>{const r=run(['concept-art-hierarchy-plan']);for(const k of ['approved_motion_language','palette','garment_silhouette','garment_structure'])assert.ok(r.json.round_plan.locked.includes(k),k);});
test('uniform detail routes to concept art hierarchy refine',()=>{const r=run(['next','--failures','detail_density_uniform']);assert.equal(r.json.recommended_round,'concept_art_hierarchy_refine');});
test('background competing routes to concept art hierarchy refine',()=>{const r=run(['next','--failures','background_contrast_competes']);assert.equal(r.json.recommended_round,'concept_art_hierarchy_refine');});
test('highlight overload routes to concept art hierarchy refine',()=>{const r=run(['next','--failures','highlight_density_overload']);assert.equal(r.json.recommended_round,'concept_art_hierarchy_refine');});
test('edge uniformity routes to concept art hierarchy refine',()=>{const r=run(['next','--failures','edge_uniform_sharpness']);assert.equal(r.json.recommended_round,'concept_art_hierarchy_refine');});
test('commercial illustration drift routes to hierarchy refine',()=>{const r=run(['next','--failures','commercial_illustration_drift']);assert.equal(r.json.recommended_round,'concept_art_hierarchy_refine');});
test('black red v081 plan keeps painterly style and beauty-first face',()=>{const r=run(['black-red-v081-plan']);assert.equal(r.json.style_stage.style_target.profile,'oriental_epic_painterly');assert.equal(r.json.style_stage.face_compatibility.resolved_face_mode,'beauty_first');assert.equal(r.json.hierarchy_stage.hierarchy.profile,'oriental_epic_concept');});
test('style failures outrank hierarchy polish failures',()=>{const r=run(['next','--failures','detail_density_uniform,style_medium_loss']);assert.equal(r.json.first_focus,'style_medium_loss');assert.equal(r.json.recommended_round,'style_target_restoration');});
test('hierarchy plan prompt explicitly reduces background and peripheral detail',()=>{const r=run(['concept-art-hierarchy-plan']);const p=r.json.prompt_skeleton.join(' ');assert.match(p,/distant architecture/);assert.match(p,/peripheral/);assert.match(p,/crisp edges/);});
