import{test}from'node:test';
import assert from'node:assert/strict';
import{spawnSync}from'node:child_process';
import path from'node:path';
import{fileURLToPath}from'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),tool=path.join(root,'scripts/iteration-director.mjs');
function run(a){const r=spawnSync(process.execPath,[tool,...a],{cwd:root,encoding:'utf8'});return{...r,json:r.stdout?JSON.parse(r.stdout):null};}

test('v0.7.2 templates validate',()=>{const r=run(['validate']);assert.equal(r.status,0,r.stderr);assert.equal(r.json.status,'pass');assert.equal(r.json.style_levels,4);assert.equal(r.json.reality_levels,4);assert.equal(r.json.render_modes,4);});
test('restoration role blocks identity and garment geometry borrowing',()=>{const r=run(['restoration-roles']);const a=r.json.references.find(x=>x.role==='style_restoration');const b=r.json.references.find(x=>x.role==='asset_master');assert.ok(a.authority.includes('motion_language'));assert.ok(a.authority.includes('lighting_language'));assert.ok(a.forbidden_authority.includes('face_identity_geometry'));assert.ok(a.forbidden_authority.includes('garment_structure'));assert.ok(b.authority.includes('asset_continuity'));});
test('hybrid render mode prioritizes identity and asset continuity',()=>{const r=run(['render-mode','--name','hybrid']);assert.equal(r.json.mode,'hybrid');assert.deepEqual(r.json.priority.slice(0,2),['identity','asset_continuity']);});
test('S2 restores style without identity geometry',()=>{const r=run(['style-level','--level','S2']);assert.equal(r.json.level,'S2');assert.ok(r.json.channels.includes('motion_language'));assert.ok(r.json.channels.includes('lighting_language'));assert.ok(r.json.forbidden_borrow.includes('face_identity_geometry'));});
test('R2 increases human material lighting realism while protecting fantasy language',()=>{const r=run(['reality-level','--level','R2']);assert.equal(r.json.level,'R2');assert.ok(r.json.human_realism.includes('regional_skin_optics'));assert.ok(r.json.material_realism.includes('layer_separation'));assert.ok(r.json.protected_style.includes('painterly_cinematic_atmosphere'));});
test('hybrid S2 R2 style plan locks structural asset channels',()=>{const r=run(['style-plan','--mode','hybrid','--style','S2','--reality','R2']);assert.equal(r.json.render_mode.mode,'hybrid');assert.ok(r.json.locks.includes('face_identity_geometry'));assert.ok(r.json.locks.includes('garment_structure'));assert.equal(r.json.reference_roles.A,'style_restoration only');assert.equal(r.json.reference_roles.B,'asset_master');});
test('style restoration round cannot copy style reference face or costume geometry',()=>{const r=run(['round','--name','style_restoration']);assert.ok(r.json.editable.includes('style_motion'));assert.ok(r.json.locked.includes('face_identity_geometry'));assert.ok(r.json.forbidden.includes('copy_style_reference_face'));assert.ok(r.json.forbidden.includes('copy_style_reference_costume_geometry'));});
test('realism merge preserves restored style channels',()=>{const r=run(['round','--name','realism_merge']);assert.ok(r.json.editable.includes('regional_skin_optics'));assert.ok(r.json.editable.includes('material_realism'));assert.ok(r.json.locked.includes('style_mood'));assert.ok(r.json.locked.includes('style_atmosphere'));assert.ok(r.json.forbidden.includes('erase_style_atmosphere'));});
test('cinematic polish changes lighting only, not semantics',()=>{const r=run(['round','--name','cinematic_polish']);assert.ok(r.json.editable.includes('lighting_reconstruction'));assert.ok(r.json.locked.includes('garment_structure'));assert.ok(r.json.forbidden.includes('semantic_redesign'));});
test('style underrestoration routes to restoration round',()=>{const r=run(['next','--failures','style_underrestored']);assert.equal(r.json.recommended_round,'style_restoration');});
test('realism undershoot routes to realism merge',()=>{const r=run(['next','--failures','realism_undershoot']);assert.equal(r.json.recommended_round,'realism_merge');});
test('flat restoration lighting routes to cinematic polish',()=>{const r=run(['next','--failures','lighting_flat_restoration']);assert.equal(r.json.recommended_round,'cinematic_polish');});
test('asset continuity drift outranks style underrestoration',()=>{const r=run(['next','--failures','style_underrestored,asset_continuity_drift']);assert.equal(r.json.first_focus,'asset_continuity_drift');});
test('conflict resolver surfaces hybrid pose conflict',()=>{const r=run(['conflict-check','--conflicts','asset_pose_vs_dynamic_style']);assert.equal(r.json.status,'needs_resolution');assert.equal(r.json.conflicts[0].id,'asset_pose_vs_dynamic_style');assert.match(r.json.conflicts[0].hybrid_resolution,/仅当动作被锁定时.*衣发与构图/);});
test('unknown conflict list can be clear',()=>{const r=run(['conflict-check','--conflicts','not_a_catalog_conflict']);assert.equal(r.json.status,'clear');assert.equal(r.json.conflicts.length,0);});
