import{test}from'node:test';import assert from'node:assert/strict';import{spawnSync}from'node:child_process';import path from'node:path';import{fileURLToPath}from'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),tool=path.join(root,'scripts/iteration-director.mjs');
function run(a){const r=spawnSync(process.execPath,[tool,...a],{cwd:root,encoding:'utf8'});return{...r,json:r.stdout?JSON.parse(r.stdout):null};}

test('v080 catalogs validate',()=>{const r=run(['validate']);assert.equal(r.status,0,r.stderr);assert.equal(r.json.status,'pass');assert.equal(r.json.style_intents,4);assert.equal(r.json.style_target_profiles,2);assert.equal(r.json.render_modes_total,5);});
test('explicit style target with asset master routes cinematic hybrid',()=>{const r=run(['style-intent','--intent','style_target_match']);assert.equal(r.json.resolved_render_mode,'cinematic_hybrid');});
test('explicit white background plus style routes style asset',()=>{const r=run(['style-intent','--intent','style_target_match','--white','true']);assert.equal(r.json.resolved_render_mode,'style_asset');});
test('prior asset does not force white background in style target plan',()=>{const r=run(['style-intent-plan','--intent','style_target_match','--style','oriental_epic_painterly']);assert.equal(r.json.style_intent.resolved_render_mode,'cinematic_hybrid');assert.match(r.json.prompt_skeleton.join(' '),/Do not inherit the Asset Master white background/);});
test('oriental epic painterly contains medium motion light atmosphere',()=>{const r=run(['style-target-profile','--profile','oriental_epic_painterly']);for(const k of ['medium_language','motion','lighting','atmosphere','composition'])assert.ok(r.json[k],k);assert.ok(r.json.anti_patterns.includes('flat_white_studio'));});
test('style target has zero authority over identity and costume geometry',()=>{const r=run(['reference-authority','--scenario','style_A_asset_B']);assert.equal(r.json.A.role,'style_target');assert.equal(r.json.A.authority.face_identity_geometry,0);assert.equal(r.json.A.authority.garment_structure,0);assert.equal(r.json.A.authority.medium_language,3);});
test('asset master remains strict identity and costume authority',()=>{const r=run(['reference-authority','--scenario','style_A_asset_B']);assert.equal(r.json.B.authority.face_identity_geometry,3);assert.equal(r.json.B.authority.garment_structure,3);});
test('cinematic preservation guard blocks studio flattening',()=>{const r=run(['style-preservation-guard','--profile','cinematic_target']);assert.ok(r.json.anti_drift.includes('flat_white_background'));assert.ok(r.json.anti_drift.includes('static_asset_pose'));});
test('painterly style recommends stylized beauty face',()=>{const r=run(['style-face-compatibility','--style','oriental_epic_painterly']);assert.equal(r.json.resolved_face_mode,'stylized_beauty');});
test('explicit humanized face can override style recommendation',()=>{const r=run(['style-face-compatibility','--style','oriental_epic_painterly','--mode','humanized_real']);assert.equal(r.json.resolved_face_mode,'humanized_real');assert.equal(r.json.override_applied,true);});
test('black-red image4 plan routes cinematic hybrid and painterly profile',()=>{const r=run(['black-red-image4-plan']);assert.equal(r.json.style_intent.resolved_render_mode,'cinematic_hybrid');assert.equal(r.json.style_target.profile,'oriental_epic_painterly');assert.equal(r.json.face_compatibility.resolved_face_mode,'stylized_beauty');});
test('style intent misroute is higher priority than style underweight',()=>{const r=run(['next','--failures','style_target_underweighted,style_intent_misroute']);assert.equal(r.json.first_focus,'style_intent_misroute');assert.equal(r.json.recommended_round,'style_intent_alignment');});
test('white background leak routes to style intent alignment',()=>{const r=run(['next','--failures','white_background_leak']);assert.equal(r.json.recommended_round,'style_intent_alignment');});
test('motion loss routes to target restoration',()=>{const r=run(['next','--failures','motion_language_loss']);assert.equal(r.json.recommended_round,'style_target_restoration');});
test('style target restoration locks identity costume and face mode',()=>{const r=run(['round','--name','style_target_restoration']);for(const id of ['face_identity_geometry','garment_silhouette','garment_structure','approved_face_mode'])assert.ok(r.json.locked.includes(id),id);assert.ok(r.json.editable.includes('style_motion'));});
test('current style target outranks archetype default conflict',()=>{const r=run(['conflict-check','--conflicts','archetype_default_vs_explicit_style_target']);assert.equal(r.json.status,'needs_resolution');assert.match(r.json.conflicts[0].resolution,/明确风格目标优先于旧角色预设/);});
